name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    - name: Set up Docker Buildx
      run : echo ${{ secrets.DOCKER_TOKEN }} | docker login ghcr.io -u munkh-altai --password-stdin    
    - name: Build the Docker image
      run: docker build . --file Dockerfile -t ghcr.io/khankhulgun/word-processor-server
    - name: Push the Docker image
      run: docker push ghcr.io/khankhulgun/word-processor-server:latest
